# Generated by Django 5.2.6 on 2025-10-14 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=100)),
                ('game', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='app1_images/')),
                ('type', models.CharField(blank=True, choices=[('fighting', 'tekken8'), ('aming', 'cod6'), ('stratigy', 'dota'), ('advancture', 'god of war')], max_length=20, null=True)),
                ('dateandtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
