# Generated by Django 5.2.6 on 2025-10-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamer',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
