# Generated by Django 5.2.6 on 2025-10-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch_1', '0002_gamer_email_gamer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='name',
            new_name='username',
        ),
    ]
