# Generated by Django 5.2.7 on 2025-11-19 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch_1', '0003_rename_name_gamer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='web_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='app1_images/')),
                ('type', models.CharField(blank=True, choices=[('student', 'student'), ('teacher', 'teacher'), ('web_user', 'web_user')], max_length=20, null=True)),
                ('dateandtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='gamer',
        ),
    ]
