# Generated by Django 5.2.7 on 2025-11-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch_1', '0004_web_user_delete_gamer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
