# Generated by Django 5.2.7 on 2025-11-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch_1', '0005_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_user',
            old_name='type',
            new_name='role',
        ),
    ]
