# Generated by Django 5.2.7 on 2025-11-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular Student'), ('monitor', 'Class Monitor'), ('prefect', 'Prefect'), ('probation', 'On Probation')], default='regular', max_length=20),
        ),
    ]
