# Generated by Django 5.2.7 on 2025-11-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
