# Generated by Django 5.2.7 on 2025-11-21 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_end_date_alter_course_start_date'),
        ('students', '0003_remove_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.course'),
        ),
    ]
