# Generated by Django 5.2.7 on 2025-11-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('assistant', 'Assistant Teacher'), ('senior', 'Senior Teacher'), ('head', 'Head Teacher'), ('temporary', 'Temporary')], default='assistant', max_length=20),
        ),
    ]
