# Generated by Django 5.2.7 on 2025-11-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subjects',
            new_name='Course',
        ),
    ]
