# Generated by Django 5.2.7 on 2025-11-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teacher', '0003_rename_subjects_teacher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Course',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='courses.course'),
        ),
    ]
