# Generated by Django 5.2.7 on 2025-11-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Course',
        ),
    ]
