# Generated by Django 5.2.7 on 2025-11-21 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teacher_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='contract_end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
