# Generated by Django 5.2.7 on 2025-11-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_end_date_alter_course_start_date'),
        ('teacher', '0007_teacher_contract_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='courses.course'),
        ),
    ]
